'use strict';

module.exports = [
          {value:"ARI", fullName: "Arizona"},
          {value:"ATL", fullName: "Atlanta"},
          {value:"BAL", fullName: "Baltimore"},
          {value:"BUF", fullName: "Buffalo"},
          {value:"CAR", fullName: "Carolina"},
          {value:"CHI", fullName: "Chicago"},
          {value:"CIN", fullName: "Cincinnati"},
          {value:"CLE", fullName: "Cleveland"},
          {value:"DAL", fullName: "Dallas"},
          {value:"DEN", fullName: "Denver"},
          {value:"DET", fullName: "Detroit"},
          {value:"GB", fullName: "Green Bay"},
          {value:"HOU", fullName: "Houston"},
          {value:"IND", fullName: "Indianapolis"},
          {value:"JAC", fullName: "Jacksonville"},
          {value:"KC", fullName: "Kansas City"},
          {value:"MIA", fullName: "Miami"},
          {value:"MIN", fullName: "Minnesota"},
          {value:"NE", fullName: "New England"},
          {value:"NO", fullName: "New Orleans"},
          {value:"NYG", fullName: "N.Y. Giants"},
          {value:"NYJ", fullName: "N.Y. Jets"},
          {value:"OAK", fullName: "Oakland"},
          {value:"PHI", fullName: "Philadelphia"},
          {value:"PIT", fullName: "Pittsburgh"},
          {value:"SD", fullName: "San Diego"},
          {value:"SF", fullName: "San Francisco"},
          {value:"SEA", fullName: "Seattle"},
          {value:"STL", fullName: "St. Louis"},
          {value:"TB", fullName: "Tampa Bay"},
          {value:"TEN", fullName: "Tennessee"},
          {value:"WAS", fullName: "Washington"}
          ];