'use strict';

module.exports = [
          {value:"ARI", fullName: "Arizona Cardinals"},
          {value:"ATL", fullName: "Atlanta Falcons"},
          {value:"BAL", fullName: "Baltimore Ravens"},
          {value:"BUF", fullName: "Buffalo Bills"},
          {value:"CAR", fullName: "Carolina Panthers"},
          {value:"CHI", fullName: "Chicago Bears"},
          {value:"CIN", fullName: "Cincinnati Bengals"},
          {value:"CLE", fullName: "Cleveland Browns"},
          {value:"DAL", fullName: "Dallas Cowboys"},
          {value:"DEN", fullName: "Denver Broncos"},
          {value:"DET", fullName: "Detroit Lions"},
          {value:"GB", fullName: "Green Bay Packers"},
          {value:"HOU", fullName: "Houston Texans"},
          {value:"IND", fullName: "Indianapolis Colts"},
          {value:"JAC", fullName: "Jacksonville Jaguars"},
          {value:"KC", fullName: "Kansas City Chiefs"},
          {value:"MIA", fullName: "Miami Dolphins"},
          {value:"MIN", fullName: "Minnesota Vikings"},
          {value:"NE", fullName: "New England Patriots"},
          {value:"NO", fullName: "New Orleans Saints"},
          {value:"NYG", fullName: "New York Giants"},
          {value:"NYJ", fullName: "New York Jets"},
          {value:"OAK", fullName: "Oakland Raiders"},
          {value:"PHI", fullName: "Philadelphia Eagles"},
          {value:"PIT", fullName: "Pittsburgh Steelers"},
          {value:"SD", fullName: "San Diego Chargers"},
          {value:"SF", fullName: "San Francisco 49ers"},
          {value:"SEA", fullName: "Seattle Seahawks"},
          {value:"STL", fullName: "St. Louis Rams"},
          {value:"TB", fullName: "Tampa Bay Buccaneers"},
          {value:"TEN", fullName: "Tennessee Titans"},
          {value:"WAS", fullName: "Washington Redskins"}
          ];