'use strict';

module.exports = [
          {value:"ATL", fullName:'Atlanta Hawks'},
          {value:"BOS", fullName:'Boston Celtics'},
          {value:"BK", fullName:'Brooklyn Nets'},
          {value:"CHAR", fullName:'Charlotte Hornets'},
          {value:"CHI", fullName:'Chicago Bulls'},
          {value:"CLE", fullName:'Cleveland Cavaliers'},
          {value:"DAL", fullName:'Dallas Mavericks'},
          {value:"DEN", fullName:'Denver Nuggets'},
          {value:"DET", fullName:'Detroit Pistons'},
          {value:"GS", fullName:'Golden State Warriors'},
          {value:"HOU", fullName:'Houston Rockets'},
          {value:"IND", fullName:'Indiana Pacers'},
          {value:"LAC", fullName:'Los Angeles Clippers'},
          {value:"LAL", fullName:'Los Angeles Lakers'},
          {value:"MEM", fullName:'Memphis Grizzlies'},
          {value:"MIA", fullName:'Miami Heat'},
          {value:"MIL", fullName:'Milwaukee Bucks'},
          {value:"MIN", fullName:'Minnesota Timberwolves'},
          {value:"NO", fullName:'New Orleans Pelicans'},
          {value:"NY", fullName:'New York Knicks'},
          {value:"OKC", fullName:'Oklahoma City Thunder'},
          {value:"ORL", fullName:'Orlando Magic'},
          {value:"PHI", fullName:'Philadelphia 76ers'},
          {value:"PHO", fullName:'Phoenix Suns'},
          {value:"POR", fullName:'Portland Trail Blazers'},
          {value:"SAC", fullName:'Sacramento Kings'},
          {value:"SA", fullName:'San Antonio Spurs'},
          {value:"TOR", fullName:'Toronto Raptors'},
          {value:"UTA", fullName:'Utah Jazz'},
          {value:"WAS", fullName:'Washington Wizards'}
          ];