'use strict';

module.exports = [
 {fullName: 'Abilene Christian', value: 'ACU'},
 {fullName: 'Air Force', value: 'AFA'},
 {fullName: 'Akron', value: 'AKR'},
 {fullName: 'Alabama', value: 'ALA'},
 {fullName: 'Alabama A&M', value: 'AAMU'},
 {fullName: 'Alabama-Birmingham', value: 'UAB'},
 {fullName: 'Alabama State', value: 'ALST'},
 {fullName: 'Albany', value: 'ALBY'},
 {fullName: 'Alcorn State', value: 'ALCN'},
 {fullName: 'Appalachian State', value: 'APP'},
 {fullName: 'Arizona', value: 'ARIZ'},
 {fullName: 'Arizona State', value: 'ASU'},
 {fullName: 'Arkansas', value: 'ARK'},
 {fullName: 'Arkansas-Pine Bluff', value: 'ARPB'},
 {fullName: 'Arkansas State', value: 'ARST'},
 {fullName: 'Army', value: 'ARMY'},
 {fullName: 'Auburn', value: 'AUB'},
 {fullName: 'Austin Peay', value: 'PEAY'},
 {fullName: 'Ball State', value: 'BALL'},
 {fullName: 'Baylor', value: 'BAY'},
 {fullName: 'Bethune Cookman', value: 'COOK'},
 {fullName: 'Boise State', value: 'BSU'},
 {fullName: 'Boston College', value: 'BC'},
 {fullName: 'Bowling Green', value: 'BGSU'},
 {fullName: 'Brigham Young', value: 'BYU'},
 {fullName: 'Buffalo', value: 'BUFF'},
 {fullName: 'California', value: 'CAL'},
 {fullName: 'Cal. Poly - SLO', value: 'CP'},
 {fullName: 'Campbell', value: 'CAMP'},
 {fullName: 'Central Arkansas', value: 'CARK'},
 {fullName: 'Central Florida', value: 'UCF'},
 {fullName: 'Central Michigan', value: 'CMU'},
 {fullName: 'Charleston Southern', value: 'CHSO'},
 {fullName: 'Charlotte', value: 'CHAR'},
 {fullName: 'Chattanooga', value: 'CHAT'},
 {fullName: 'Cincinnati', value: 'CIN'},
 {fullName: 'Clemson', value: 'CLEM'},
 {fullName: 'Coastal Carolina', value: 'CCAR'},
 {fullName: 'Colgate', value: 'COLG'},
 {fullName: 'Colorado', value: 'COLO'},
 {fullName: 'Colorado State', value: 'CSU'},
 {fullName: 'Connecticut', value: 'CONN'},
 {fullName: 'Delaware', value: 'DEL'},
 {fullName: 'Delaware State', value: 'DSU'},
 {fullName: 'Duke', value: 'DUKE'},
 {fullName: 'Duquesne', value: 'DUQ'},
 {fullName: 'East Carolina', value: 'ECU'},
 {fullName: 'Eastern Illinois', value: 'EIU'},
 {fullName: 'Eastern Kentucky', value: 'EKY'},
 {fullName: 'Eastern Michigan', value: 'EMU'},
 {fullName: 'Eastern Washington', value: 'EWU'},
 {fullName: 'Elon University', value: 'ELON'},
 {fullName: 'Florida', value: 'FLA'},
 {fullName: 'Florida A&M', value: 'FAMU'},
 {fullName: 'Florida Atlantic', value: 'FAU'},
 {fullName: 'Florida International', value: 'FIU'},
 {fullName: 'Florida State', value: 'FSU'},
 {fullName: 'Fordham', value: 'FOR'},
 {fullName: 'Fresno State', value: 'FRES'},
 {fullName: 'Furman', value: 'FUR'},
 {fullName: 'Gardner Webb', value: 'WEBB'},
 {fullName: 'Georgia', value: 'UGA'},
 {fullName: 'Georgia Southern', value: 'GASO'},
 {fullName: 'Georgia State', value: 'GSU'},
 {fullName: 'Georgia Tech', value: 'GT'},
 {fullName: 'Grambling State', value: 'GRAM'},
 {fullName: 'Hampton', value: 'HAMP'},
 {fullName: 'Hawaii', value: 'HAW'},
 {fullName: 'Houston', value: 'HOU'},
 {fullName: 'Howard', value: 'HOW'},
 {fullName: 'Idaho', value: 'IDHO'},
 {fullName: 'Idaho State', value: 'IDST'},
 {fullName: 'Illinois', value: 'ILL'},
 {fullName: 'Illinois State', value: 'ILST'},
 {fullName: 'Incarnate Word', value: 'IW'},
 {fullName: 'Indiana', value: 'IND'},
 {fullName: 'Indiana State', value: 'INST'},
 {fullName: 'Iowa', value: 'IOWA'},
 {fullName: 'Iowa State', value: 'ISU'},
 {fullName: 'Jackson State', value: 'JKST'},
 {fullName: 'Jacksonville State', value: 'JVST'},
 {fullName: 'James Madison', value: 'JMU'},
 {fullName: 'Kansas', value: 'KU'},
 {fullName: 'Kansas State', value: 'KSU'},
 {fullName: 'Kent State', value: 'KENT'},
 {fullName: 'Kentucky', value: 'UK'},
 {fullName: 'Lamar', value: 'LAM'},
 {fullName: 'Liberty', value: 'LIB'},
 {fullName: 'Louisiana State', value: 'LSU'},
 {fullName: 'Louisiana Tech', value: 'LT'},
 {fullName: 'Louisville', value: 'LOU'},
 {fullName: 'Maine', value: 'ME'},
 {fullName: 'Marshall', value: 'MRSH'},
 {fullName: 'Maryland', value: 'MD'},
 {fullName: 'Massachusetts', value: 'MASS'},
 {fullName: 'McNeese State', value: 'MCNS'},
 {fullName: 'Memphis', value: 'MEM'},
 {fullName: 'Miami', value: 'MIA'},
 {fullName: 'Miami (Ohio)', value: 'M-OH'},
 {fullName: 'Michigan', value: 'MICH'},
 {fullName: 'Michigan State', value: 'MSU'},
 {fullName: 'Middle Tennessee', value: 'MTU'},
 {fullName: 'Minnesota', value: 'MINN'},
 {fullName: 'Mississippi', value: 'MISS'},
 {fullName: 'Mississippi State', value: 'MSST'},
 {fullName: 'Mississippi Valley State', value: 'MVSU'},
 {fullName: 'Missouri', value: 'MIZZ'},
 {fullName: 'Missouri State', value: 'MOSU'},
{fullName: 'Monmouth', value: 'MONM'},
 {fullName: 'Montana', value: 'MONT'},
 {fullName: 'Montana State', value: 'MTST'},
 {fullName: 'Morgan State', value: 'MORG'},
 {fullName: 'Murray State', value: 'MURR'},
 {fullName: 'Navy', value: 'NAVY'},
 {fullName: 'Nebraska', value: 'NEB'},
 {fullName: 'Nevada', value: 'NEV'},
 {fullName: 'New Hampshire', value: 'UNH'},
 {fullName: 'New Mexico', value: 'UNM'},
 {fullName: 'New Mexico State', value: 'NMSU'},
 {fullName: 'Nicholls State', value: 'NICH'},
 {fullName: 'Norfolk State', value: 'NORF'},
 {fullName: 'North Carolina', value: 'UNC'},
 {fullName: 'North Carolina A&T', value: 'NCAT'},
 {fullName: 'North Carolina Central', value: 'NCCU'},
 {fullName: 'North Carolina State', value: 'NCST'},
 {fullName: 'North Dakota', value: 'UND'},
 {fullName: 'North Dakota State', value: 'NDSU'},
 {fullName: 'Northern Arizona', value: 'NAU'},
 {fullName: 'Northern Colorado', value: 'UNCO'},
 {fullName: 'Northern Illinois', value: 'NIU'},
 {fullName: 'Northern Iowa', value: 'UNI'},
 {fullName: 'North Texas', value: 'UNT'},
 {fullName: 'Northwestern', value: 'NW'},
 {fullName: 'Northwestern Oklahoma State', value: 'NWOK'},
 {fullName: 'Northwestern State', value: 'NWST'},
 {fullName: 'Notre Dame', value: 'ND'},
 {fullName: 'Ohio', value: 'OHIO'},
 {fullName: 'Ohio State', value: 'OSU'},
 {fullName: 'Oklahoma', value: 'OKLA'},
 {fullName: 'Oklahoma State', value: 'OKST'},
 {fullName: 'Old Dominion', value: 'ODU'},
 {fullName: 'Oregon', value: 'ORE'},
 {fullName: 'Oregon State', value: 'ORST'},
 {fullName: 'Penn State', value: 'PSU'},
 {fullName: 'Pittsburgh', value: 'PITT'},
 {fullName: 'Portland State', value: 'PRST'},
 {fullName: 'Prairie View A&M', value: 'PV'},
 {fullName: 'Presbyterian', value: 'PRE'},
 {fullName: 'Purdue', value: 'PUR'},
 {fullName: 'Rhode Island', value: 'URI'},
 {fullName: 'Rice', value: 'RICE'},
 {fullName: 'Richmond', value: 'RICH'},
 {fullName: 'Rutgers', value: 'RUTG'},
 {fullName: 'Sacramento State', value: 'CSUS'},
 {fullName: 'Samford', value: 'SAM'},
 {fullName: 'Sam Houston State', value: 'SHSU'},
 {fullName: 'San Diego', value: 'USD'},
 {fullName: 'San Diego State', value: 'SDSU'},
 {fullName: 'San Jose State', value: 'SJSU'},
 {fullName: 'Savannah State', value: 'SAV'},
 {fullName: 'SE Missouri State', value: 'SEMST'},
 {fullName: 'South Alabama', value: 'USA'},
{fullName: 'South Carolina', value: 'SOCAR'},
 {fullName: 'South Carolina State', value: 'SCST'},
 {fullName: 'South Dakota', value: 'SDAK'},
 {fullName: 'South Dakota State', value: 'SDST'},
 {fullName: 'Southeastern Louisiana', value: 'SELA'},
 {fullName: 'Southern', value: 'SOUTH'},
 {fullName: 'Southern California', value: 'USC'},
 {fullName: 'Southern Illinois', value: 'SIU'},
 {fullName: 'Southern Methodist', value: 'SMU'},
 {fullName: 'Southern Mississippi', value: 'SOMIS'},
 {fullName: 'Southern Utah', value: 'SUU'},
 {fullName: 'South Florida', value: 'USF'},
 {fullName: 'Stanford', value: 'STAN'},
 {fullName: 'Stephen F. Austin', value: 'SFA'},
 {fullName: 'Stony Brook', value: 'STON'},
 {fullName: 'Syracuse', value: 'SYR'},
 {fullName: 'Temple', value: 'TEM'},
 {fullName: 'Tennessee', value: 'TENN'},
 {fullName: 'Tennessee-Martin', value: 'UTM'},
 {fullName: 'Tennessee State', value: 'TNST'},
 {fullName: 'Tennessee Tech', value: 'TNTC'},
 {fullName: 'Texas', value: 'TEX'},
 {fullName: 'Texas A&M', value: 'TAM'},
 {fullName: 'Texas A&M-Commerce', value: 'TXAM-C'},
 {fullName: 'Texas Christian', value: 'TCU'},
 {fullName: 'Texas El Paso', value: 'UTEP'},
 {fullName: 'Texas-San Antonio', value: 'UTSA'},
 {fullName: 'Texas Southern', value: 'TXSO'},
 {fullName: 'Texas State', value: 'TXST'},
 {fullName: 'Texas Tech', value: 'TTU'},
 {fullName: 'The Citadel', value: 'CIT'},
 {fullName: 'Toledo', value: 'TOL'},
 {fullName: 'Towson', value: 'TOWS'},
 {fullName: 'Troy', value: 'TROY'},
 {fullName: 'Tulane', value: 'TULN'},
 {fullName: 'Tulsa', value: 'TLSA'},
 {fullName: 'UC - Davis', value: 'UCD'},
 {fullName: 'UCLA', value: 'UCLA'},
 {fullName: 'UL Lafayette', value: 'ULL'},
 {fullName: 'UL Monroe', value: 'ULM'},
 {fullName: 'UNLV', value: 'UNLV'},
 {fullName: 'Utah', value: 'UTAH'},
 {fullName: 'Utah State', value: 'USU'},
 {fullName: 'Vanderbilt', value: 'VAN'},
 {fullName: 'Villanova', value: 'VILL'},
 {fullName: 'Virginia', value: 'UVA'},
 {fullName: 'Virginia Military', value: 'VMI'},
 {fullName: 'Virginia Tech', value: 'VT'},
 {fullName: 'Wagner', value: 'WAG'},
 {fullName: 'Wake Forest', value: 'WAKE'},
 {fullName: 'Washington', value: 'WASH'},
 {fullName: 'Washington State', value: 'WSU'},
 {fullName: 'Weber State', value: 'WEB'},
 {fullName: 'Western Carolina', value: 'WCU'},
 {fullName: 'Western Illinois', value: 'WIU'},
 {fullName: 'Western Kentucky', value: 'WKU'},
 {fullName: 'Western Michigan', value: 'WMU'},
 {fullName: 'West Virginia', value: 'WVU'},
 {fullName: 'William & Mary', value: 'CWM'},
 {fullName: 'Wisconsin', value: 'WIS'},
 {fullName: 'Wofford', value: 'WOF'},
 {fullName: 'Wyoming', value: 'WYO'},
 {fullName: 'Yale', value: 'YALE'},
 {fullName: 'Youngstown State', value: 'YSU'}
          ];

