'use strict';

module.exports = [

 {value: "America East", fullName: "America East"},
 {value: "American Athletic Conference", fullName: "AAC"},
 {value: "Atlantic 10", fullName: "Atlantic 10"},
 {value: "Atlantic Coast", fullName: "ACC"},
 {value: "Atlantic Sun", fullName: "Atlantic Sun"},
 {value: "Big 12", fullName: "Big 12"},
 {value: "Big East", fullName: "Big East"},
 {value: "Big Sky", fullName: "Big Sky"},
 {value: "Big South", fullName: "Big South"},
 {value: "Big Ten", fullName: "Big Ten"},
 {value: "Big West", fullName: "Big West"},
 {value: "Colonial Athletic Association", fullName: "Colonial"},
 {value: "Conference USA", fullName: "C-USA"},
 {value: "Horizon League", fullName: "Horizon"},
 {value: "Ivy League", fullName: "Ivy League"},
 {value: "Metro Atlantic Athletic", fullName: "MAAC"},
 {value: "Mid-American", fullName: "MAC"},
 {value: "Mid-Eastern Athletic", fullName: "MEAC"},
 {value: "Missouri Valley", fullName: "Missouri Valley"},
 {value: "Mountain West", fullName: "Mountain West"},
 {value: "Northeast", fullName: "Northeast"},
 {value: "Ohio Valley", fullName: "Ohio Valley"},
 {value: "Pacific-12", fullName: "Pac-12"},
 {value: "Patriot League", fullName: "Patriot League"},
 {value: "Southeastern", fullName: "SEC"},
 {value: "Southern", fullName: "Southern"},
 {value: "Southland", fullName: "Southland"},
 {value: "Southwestern Athletic", fullName: "SWAC"},
 {value: "Summit", fullName: "Summit League"},
 {value: "Sun Belt", fullName: "Sun Belt"},
 {value: "West Coast", fullName: "West Coast Conference"},
 {value: "Western Athletic", fullName: "WAC"}
];