'use strict';

module.exports = [

{value: "ACU", fullName: "Abilene Christian"},
{value: "AFA", fullName: "Air Force"},
{value: "AKR", fullName: "Akron"},
{value: "ALA", fullName: "Alabama"},
{value: "AAMU", fullName: "Alabama A&M"},
{value: "ALST", fullName: "Alabama St."},
{value: "ALSKA", fullName: "Alaska - Anchorage"},
{value: "ALBY", fullName: "Albany"},
{value: "ALCN", fullName: "Alcorn St."},
{value: "AMER", fullName: "American U."},
{value: "APP", fullName: "Appalachian St."},
{value: "ARIZ", fullName: "Arizona"},
{value: "ASU", fullName: "Arizona State"},
{value: "ARK", fullName: "Arkansas"},
{value: "UALR", fullName: "Arkansas-Little Rock"},
{value: "ARPB", fullName: "Arkansas-Pine Bluff"},
{value: "ARST", fullName: "Arkansas St."},
{value: "ARMY", fullName: "Army"},
{value: "AUB", fullName: "Auburn"},
{value: "PEAY", fullName: "Austin Peay"},
{value: "BALL", fullName: "Ball St."},
{value: "BAY", fullName: "Baylor"},
{value: "BEL", fullName: "Belmont"},
{value: "COOK", fullName: "Bethune-Cookman"},
{value: "BING", fullName: "Binghamton"},
{value: "BSU", fullName: "Boise St."},
{value: "BC", fullName: "Boston College"},
{value: "BU", fullName: "Boston U"},
{value: "BGSU", fullName: "Bowling Green"},
{value: "BRAD", fullName: "Bradley"},
{value: "BYU", fullName: "Brigham Young"},
{value: "BRWN", fullName: "Brown"},
{value: "BRY", fullName: "Bryant"},
{value: "BUCK", fullName: "Bucknell"},
{value: "BUFF", fullName: "Buffalo"},
{value: "BUT", fullName: "Butler"},
{value: "CAL", fullName: "California"},
{value: "CP", fullName: "Cal Poly SLO"},
{value: "CSB", fullName: "Cal. State - Bakersfield"},
{value: "CSF", fullName: "Cal St. Fullerton"},
{value: "CAMP", fullName: "Campbell"},
{value: "CAN", fullName: "Canisius"},
{value: "CENT", fullName: "Centenary"},
{value: "CARK", fullName: "Central Arkansas"},
{value: "CCSU", fullName: "Central Conn. St."},
{value: "UCF", fullName: "Central Florida"},
{value: "CMU", fullName: "Central Michigan"},
{value: "CHAMIN", fullName: "Chaminade"},
{value: "COFC", fullName: "Charleston"},
{value: "CHSO", fullName: "Charleston Southern"},
{value: "CHAR", fullName: "Charlotte"},
{value: "CHAT", fullName: "Chattanooga"},
{value: "CHS", fullName: "Chicago St."},
{value: "CIN", fullName: "Cincinnati"},
{value: "CLEM", fullName: "Clemson"},
{value: "CLEV", fullName: "Cleveland St."},
{value: "CCAR", fullName: "Coastal Carolina"},
{value: "COLG", fullName: "Colgate"},
{value: "COLO", fullName: "Colorado"},
{value: "CSU", fullName: "Colorado St."},
{value: "CLMB", fullName: "Columbia"},
{value: "UCONN", fullName: "Connecticut"},
{value: "COPP", fullName: "Coppin St."},
{value: "COR", fullName: "Cornell"},
{value: "CRE", fullName: "Creighton"},
{value: "CSN", fullName: "CSU Northridge"},
{value: "DART", fullName: "Dartmouth"},
{value: "DAV", fullName: "Davidson"},
{value: "DAY", fullName: "Dayton"},
{value: "DEL", fullName: "Delaware"},
{value: "DSU", fullName: "Delaware State"},
{value: "DEN", fullName: "Denver"},
{value: "DEP", fullName: "DePaul"},
{value: "DET", fullName: "Detroit"},
{value: "DRKE", fullName: "Drake"},
{value: "DREX", fullName: "Drexel"},
{value: "DUKE", fullName: "Duke"},
{value: "DUQ", fullName: "Duquesne"},
{value: "ECU", fullName: "East Carolina"},
{value: "EIU", fullName: "Eastern Illinois"},
{value: "EKY", fullName: "Eastern Kentucky"},
{value: "EMU", fullName: "Eastern Michigan"},
{value: "EWU", fullName: "Eastern Washington"},
{value: "ETSU", fullName: "East Tennessee St."},
{value: "ELON", fullName: "Elon University"},
{value: "EVAN", fullName: "Evansville"},
{value: "FAIR", fullName: "Fairfield"},
{value: "FDU", fullName: "Fairleigh Dickinson"},
{value: "FLA", fullName: "Florida"},
{value: "FAMU", fullName: "Florida A&M"},
{value: "FAU", fullName: "Florida Atlantic"},
{value: "FGCU", fullName: "Florida Gulf Coast"},
{value: "FIU", fullName: "Florida International"},
{value: "FSU", fullName: "Florida St."},
{value: "FOR", fullName: "Fordham"},
{value: "FRES", fullName: "Fresno St."},
{value: "FUR", fullName: "Furman"},
{value: "WEBB", fullName: "Gardner-Webb"},
{value: "GMU", fullName: "George Mason"},
{value: "GTWN", fullName: "Georgetown"},
{value: "GW", fullName: "George Washington"},
{value: "UGA", fullName: "Georgia"},
{value: "GASO", fullName: "Georgia Southern"},
{value: "GSU", fullName: "Georgia St"},
{value: "GT", fullName: "Georgia Tech"},
{value: "GONZ", fullName: "Gonzaga"},
{value: "GRAM", fullName: "Grambling State"},
{value: "GRC", fullName: "Grand Canyon"},
{value: "GB", fullName: "Green Bay"},
{value: "HAMP", fullName: "Hampton"},
{value: "HART", fullName: "Hartford"},
{value: "HARV", fullName: "Harvard"},
{value: "HAW", fullName: "Hawaii"},
{value: "HP", fullName: "High Point"},
{value: "HOF", fullName: "Hofstra"},
{value: "HC", fullName: "Holy Cross"},
{value: "HOU", fullName: "Houston"},
{value: "HBU", fullName: "Houston Baptist"},
{value: "HOW", fullName: "Howard"},
{value: "IDHO", fullName: "Idaho"},
{value: "IDST", fullName: "Idaho State"},
{value: "ILL", fullName: "Illinois"},
{value: "UIC", fullName: "Illinois-Chicago"},
{value: "ILST", fullName: "Illinois St."},
{value: "IW", fullName: "Incarnate Word"},
{value: "IND", fullName: "Indiana"},
{value: "INDPU", fullName: "Indiana - Purdue"},
{value: "INST", fullName: "Indiana St."},
{value: "IONA", fullName: "Iona"},
{value: "IOWA", fullName: "Iowa"},
{value: "ISU", fullName: "Iowa St."},
{value: "IPFW", fullName: "IUPU - Ft. Wayne"},
{value: "JKST", fullName: "Jackson State"},
{value: "JAC", fullName: "Jacksonville"},
{value: "JVST", fullName: "Jacksonville St."},
{value: "JMU", fullName: "James Madison"},
{value: "KU", fullName: "Kansas"},
{value: "KSU", fullName: "Kansas St."},
{value: "KENN", fullName: "Kennesaw St."},
{value: "KENT", fullName: "Kent St."},
{value: "UK", fullName: "Kentucky"},
{value: "LAF", fullName: "Lafayette"},
{value: "LAM", fullName: "Lamar"},
{value: "LAS", fullName: "La Salle"},
{value: "LASR", fullName: "La Sierra University"},
{value: "LEH", fullName: "Lehigh"},
{value: "LIB", fullName: "Liberty"},
{value: "LIP", fullName: "Lipscomb"},
{value: "LIU", fullName: "LIU Brooklyn"},
{value: "LBSU", fullName: "Long Beach St."},
{value: "LONG", fullName: "Longwood"},
{value: "ULL", fullName: "Louisiana-Lafayette"},
{value: "ULM", fullName: "Louisiana-Monroe"},
{value: "LSU", fullName: "Louisiana State"},
{value: "LT", fullName: "Louisiana Tech"},
{value: "LOU", fullName: "Louisville"},
{value: "L-IL", fullName: "Loyola-Chicago"},
{value: "L-MD", fullName: "Loyola-Maryland"},
{value: "LMU", fullName: "Loyola Marymount"},
{value: "ME", fullName: "Maine"},
{value: "MAN", fullName: "Manhattan"},
{value: "MRST", fullName: "Marist"},
{value: "MARQ", fullName: "Marquette"},
{value: "MRSH", fullName: "Marshall"},
{value: "MD", fullName: "Maryland"},
{value: "UMES", fullName: "Maryland - E. Shore"},
{value: "MASS", fullName: "Massachusetts"},
{value: "MCNS", fullName: "McNeese St."},
{value: "UMBC", fullName: "MD Baltimore Cty"},
{value: "MEM", fullName: "Memphis"},
{value: "MER", fullName: "Mercer"},
{value: "MIA", fullName: "Miami-Florida"},
{value: "M-OH", fullName: "Miami (OH)"},
{value: "MICH", fullName: "Michigan"},
{value: "MSU", fullName: "Michigan St"},
{value: "MTU", fullName: "Middle Tennessee St."},
{value: "MINN", fullName: "Minnesota"},
{value: "MISS", fullName: "Mississippi"},
{value: "MSST", fullName: "Mississippi St."},
{value: "MVSU", fullName: "Mississippi Valley State"},
{value: "MIZZ", fullName: "Missouri"},
{value: "MOSU", fullName: "Missouri St."},
{value: "MONM", fullName: "Monmouth-NJ"},
{value: "MONT", fullName: "Montana"},
{value: "MTST", fullName: "Montana St."},
{value: "MORE", fullName: "Morehead St."},
{value: "MORG", fullName: "Morgan St."},
{value: "MSM", fullName: "Mount St. Mary's"},
{value: "MURR", fullName: "Murray St."},
{value: "NAVY", fullName: "Navy"},
{value: "UNCA", fullName: "N.C. Asheville"},
{value: "UNCG", fullName: "NC-Greensboro"},
{value: "NCST", fullName: "N.C. State"},
{value: "UNCW", fullName: "NC-Wilmington"},
{value: "NEB", fullName: "Nebraska"},
{value: "NEOM", fullName: "Nebraska Omaha"},
{value: "NEV", fullName: "Nevada"},
{value: "UNH", fullName: "New Hampshire"},
{value: "NJIT", fullName: "New Jersey Tech"},
{value: "UNM", fullName: "New Mexico"},
{value: "NMSU", fullName: "New Mexico St."},
{value: "UNO", fullName: "New Orleans"},
{value: "NIAG", fullName: "Niagara"},
{value: "NICH", fullName: "Nicholls State"},
{value: "NCAT", fullName: "No.Carolina A&T"},
{value: "NORF", fullName: "Norfolk State"},
{value: "UNC", fullName: "North Carolina"},
{value: "NCCU", fullName: "North Carolina Central"},
{value: "UND", fullName: "North Dakota"},
{value: "NDSU", fullName: "North Dakota State"},
{value: "NE", fullName: "Northeastern"},
{value: "NAU", fullName: "Northern Arizona"},
{value: "UNCO", fullName: "Northern Colorado"},
{value: "NIU", fullName: "Northern Illinois"},
{value: "UNI", fullName: "Northern Iowa"},
{value: "NKU", fullName: "Northern Kentucky"},
{value: "UNF", fullName: "North Florida"},
{value: "UNT", fullName: "North Texas"},
{value: "NW", fullName: "Northwestern"},
{value: "NWST", fullName: "Northwestern St."},
{value: "ND", fullName: "Notre Dame"},
{value: "OAK", fullName: "Oakland"},
{value: "OHIO", fullName: "Ohio"},
{value: "OSU", fullName: "Ohio St."},
{value: "OKLA", fullName: "Oklahoma"},
{value: "OKST", fullName: "Oklahoma St."},
{value: "ODU", fullName: "Old Dominion"},
{value: "ORU", fullName: "Oral Roberts"},
{value: "ORE", fullName: "Oregon"},
{value: "ORST", fullName: "Oregon St."},
{value: "PAC", fullName: "Pacific"},
{value: "PSU", fullName: "Penn St."},
{value: "PENN", fullName: "Pennsylvania"},
{value: "PEPP", fullName: "Pepperdine"},
{value: "PITT", fullName: "Pittsburgh"},
{value: "PORT", fullName: "Portland"},
{value: "PRST", fullName: "Portland St."},
{value: "PV", fullName: "Prairie View A&M"},
{value: "PRE", fullName: "Presbyterian"},
{value: "PRIN", fullName: "Princeton"},
{value: "PROV", fullName: "Providence"},
{value: "PUR", fullName: "Purdue"},
{value: "QUIN", fullName: "Quinnipiac"},
{value: "RAD", fullName: "Radford"},
{value: "URI", fullName: "Rhode Island"},
{value: "RICE", fullName: "Rice"},
{value: "RICH", fullName: "Richmond"},
{value: "RID", fullName: "Rider"},
{value: "RMU", fullName: "Robert Morris"},
{value: "ROCH", fullName: "Rochester College"},
{value: "RUTG", fullName: "Rutgers"},
{value: "CSUS", fullName: "Sacramento State"},
{value: "SHU", fullName: "Sacred Heart"},
{value: "SLU", fullName: "Saint Louis"},
{value: "SAM", fullName: "Samford"},
{value: "SHSU", fullName: "Sam Houston St."},
{value: "USD", fullName: "San Diego"},
{value: "SDSU", fullName: "San Diego St."},
{value: "SF", fullName: "San Francisco"},
{value: "SJSU", fullName: "San Jose St."},
{value: "SCU", fullName: "Santa Clara"},
{value: "SAV", fullName: "Savannah State"},
{value: "SEA", fullName: "Seattle"},
{value: "SEMO", fullName: "SE Missouri St."},
{value: "HALL", fullName: "Seton Hall"},
{value: "SIE", fullName: "Siena"},
{value: "SIUE", fullName: "SIU - Edwardsville"},
{value: "USA", fullName: "South Alabama"},
{value: "SCAR", fullName: "South Carolina"},
{value: "SCST", fullName: "South Carolina State"},
{value: "SCUS", fullName: "South Carolina Upstate"},
{value: "SDAK", fullName: "South Dakota"},
{value: "SDST", fullName: "South Dakota State"},
{value: "SELA", fullName: "Southeastern Louisiana"},
{value: "SOU", fullName: "Southern"},
{value: "USC", fullName: "Southern California"},
{value: "SIU", fullName: "Southern Illinois"},
{value: "SMU", fullName: "Southern Methodist"},
{value: "USM", fullName: "Southern Miss"},
{value: "SUU", fullName: "Southern Utah"},
{value: "USF", fullName: "South Florida"},
{value: "STAN", fullName: "Stanford"},
{value: "SBON", fullName: "St. Bonaventure"},
{value: "SFA", fullName: "Stephen F. Austin"},
{value: "STET", fullName: "Stetson"},
{value: "SFNY", fullName: "St. Francis (NY)"},
{value: "SFPA", fullName: "St. Francis (PA)"},
{value: "SJU", fullName: "St. John's"},
{value: "JOES", fullName: "St. Joseph's"},
{value: "SMC", fullName: "St. Mary's"},
{value: "STON", fullName: "Stony Brook"},
{value: "SPC", fullName: "St. Peter's"},
{value: "SYR", fullName: "Syracuse"},
{value: "TEM", fullName: "Temple"},
{value: "TENN", fullName: "Tennessee"},
{value: "TNST", fullName: "Tennessee St."},
{value: "TNTC", fullName: "Tennessee Tech"},
{value: "UTM", fullName: "Tenn-Martin"},
{value: "TEX", fullName: "Texas"},
{value: "TAM", fullName: "Texas A&M"},
{value: "AMCC", fullName: "Texas A&M CC"},
{value: "UTA", fullName: "Texas-Arlington"},
{value: "TCU", fullName: "Texas Christian"},
{value: "UTEP", fullName: "Texas-El Paso"},
{value: "UTRGV", fullName: "Texas Rio Grande Valley"},
{value: "UTSA", fullName: "Texas-San Antonio"},
{value: "TXSO", fullName: "Texas Southern"},
{value: "TXST", fullName: "Texas State"},
{value: "TTU", fullName: "Texas Tech"},
{value: "CIT", fullName: "The Citadel"},
{value: "TOL", fullName: "Toledo"},
{value: "TOWS", fullName: "Towson"},
{value: "TROY", fullName: "Troy"},
{value: "TULN", fullName: "Tulane"},
{value: "TLSA", fullName: "Tulsa"},
{value: "UAB", fullName: "UAB"},
{value: "UCD", fullName: "UC Davis"},
{value: "UCI", fullName: "UC Irvine"},
{value: "UCLA", fullName: "UCLA"},
{value: "UCRV", fullName: "UC Riverside"},
{value: "UCSB", fullName: "UC Santa Barbara"},
{value: "UMKC", fullName: "UMKC"},
{value: "UNLV", fullName: "UNLV"},
{value: "UTAH", fullName: "Utah"},
{value: "USU", fullName: "Utah St."},
{value: "UVU", fullName: "Utah Valley"},
{value: "VALP", fullName: "Valparaiso"},
{value: "VAN", fullName: "Vanderbilt"},
{value: "VCU", fullName: "VCU"},
{value: "UVM", fullName: "Vermont"},
{value: "VILL", fullName: "Villanova"},
{value: "UVA", fullName: "Virginia"},
{value: "VT", fullName: "Virginia Tech"},
{value: "VMI", fullName: "VMI"},
{value: "WAG", fullName: "Wagner"},
{value: "WAKE", fullName: "Wake Forest"},
{value: "WASH", fullName: "Washington"},
{value: "WSU", fullName: "Washington St."},
{value: "WEB", fullName: "Weber St."},
{value: "WALAB", fullName: "West Alabama"},
{value: "WCU", fullName: "Western Carolina"},
{value: "WIU", fullName: "Western Illinois"},
{value: "WKU", fullName: "Western Kentucky"},
{value: "WMU", fullName: "Western Michigan"},
{value: "WNMEX", fullName: "Western New Mexico"},
{value: "WVU", fullName: "West Virginia"},
{value: "WICH", fullName: "Wichita St."},
{value: "CWM", fullName: "William & Mary"},
{value: "WIN", fullName: "Winthrop"},
{value: "WIS", fullName: "Wisconsin"},
{value: "MILW", fullName: "Wis.-Milwaukee"},
{value: "WOF", fullName: "Wofford"},
{value: "WRST", fullName: "Wright St."},
{value: "WYO", fullName: "Wyoming"},
{value: "XAV", fullName: "Xavier"},
{value: "YALE", fullName: "Yale"},
{value: "YSU", fullName: "Youngstown St."}
];