'use strict';

module.exports = [
          {value:"ATL", name:'Atlanta Hawks'},
          {value:"BOS", name:'Boston Celtics'},
          {value:"BK", name:'Brooklyn Nets'},
          {value:"CHAR", name:'Charlotte Hornets'},
          {value:"CHI", name:'Chicago Bulls'},
          {value:"CLE", name:'Cleveland Cavaliers'},
          {value:"DAL", name:'Dallas Mavericks'},
          {value:"DEN", name:'Denver Nuggets'},
          {value:"DET", name:'Detroit Pistons'},
          {value:"GS", name:'Golden State Warriors'},
          {value:"HOU", name:'Houston Rockets'},
          {value:"IND", name:'Indiana Pacers'},
          {value:"LAC", name:'Los Angeles Clippers'},
          {value:"LAL", name:'Los Angeles Lakers'},
          {value:"MEM", name:'Memphis Grizzlies'},
          {value:"MIA", name:'Miami Heat'},
          {value:"MIL", name:'Milwaukee Bucks'},
          {value:"MIN", name:'Minnesota Timberwolves'},
          {value:"NO", name:'New Orleans Pelicans'},
          {value:"NY", name:'New York Knicks'},
          {value:"OKC", name:'Oklahoma City Thunder'},
          {value:"ORL", name:'Orlando Magic'},
          {value:"PHI", name:'Philadelphia 76ers'},
          {value:"PHO", name:'Phoenix Suns'},
          {value:"POR", name:'Portland Trail Blazers'},
          {value:"SAC", name:'Sacramento Kings'},
          {value:"SA", name:'San Antonio Spurs'},
          {value:"TOR", name:'Toronto Raptors'},
          {value:"UTA", name:'Utah Jazz'},
          {value:"WAS", name:'Washington Wizards'}
          ];